$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: main
endpoint_name: deberta-large-mnli
model: azureml://registries/HuggingFace/models/microsoft-deberta-large-mnli/versions/9
environment:
  name: deberta-large-mnli-env
  description: Environment for microsoft/deberta-large-mnli model
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
  conda_file: conda.yml
instance_type: Standard_NC4as_T4_v3
instance_count: 1
environment_variables:
  HF_HUB_ENABLE_HF_TRANSFER: "1"
  TRANSFORMERS_NO_ADVISORY_WARNINGS: "1"

